charts/cui-ra/Chart.yaml
=> removed redis from charts

charts/cui-ra/values.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> added readiness delays

charts/cui-ra/values.yaml
=> fixed chart key

src/main/views/intro.njk
Amend block to allow contact section to be rendered
```
[ ] Yes
[ X] No
```
=> Amended block to pull in contact section

config/default.json
N/A
Update Redis port to SSL port
```
[ ] Yes
[X] No
```
=> Update redis port to SSL

src/main/controllers/demoController.ts, src/main/routes.ts, src/main/views/demo.njk, src/test/unit/tests/controllers/demoController.test.ts
N/A
N/A
```
[ ] Yes
[X] No
```
=> Changed form submit to get instead of post

src/main/modules/session/index.ts
N/A
N/A
```
[ ] Yes
[X] No
```
=> C UI ra 22

src/main/modules/session/index.ts
N/A
Amended wy tls is set conditionally
```
[ ] Yes
[X] No
```
=> amended way tls is set conditionally

src/main/resources/translation/en/common.json
https://tools.hmcts.net/jira/browse/CUIRA-145
updated text for review page
```
[ ] Yes
[X] No
```
=> updated text

src/main/resources/translation/en/common.json
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> C UI ra 145

src/main/routes.ts
Added return statements to prevent additional code running on 'back' route
```
[ ] Yes
[X] No
```
=> C UI ra 44

src/main/constants/route.ts
fix the get api call
```
[ ] Yes
[X] No
```
=> fix api get route

src/main/constants/route.ts, src/main/controllers/formController.ts, src/main/views/review.njk, src/test/unit/tests/controllers/formController.test.ts
pass a change query to the url and keep it going through the journey
```
[ ] Yes
[X] No
```
=> pass change query and continue it forward

src/main/builders/payloadBuilder.ts, src/main/controllers/dataController.ts, src/main/models/inboundPayload.ts, src/main/types/index.d.ts
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
payload to output corrolation id
```
[ ] Yes
[ ] No
```
=> output corrolation id

src/main/views/forms/checkbox-group.njk
https://tools.hmcts.net/jira/browse/CUIRA-200
added labelledby to textarea for more descriptive label
=> added labelledby on textarea input

src/main/schemas/InboundPayload.ts
fixed api post schema. changed CallbackURL to CallbackUrl in schema same with LogoutURL
=> fixed callbackUrl and logoutUrl schmea

src/main/schemas/InboundPayload.ts
=> changed required

src/main/controllers/dataController.ts
bug fix: in datacontroller the find method for master was using flagCode instead of value.flagcode
=> bug find master code

infrastructure/state.tf
=> Update azurerm version in state.tf

charts/cui-ra/Chart.yaml
=> revert node version in charts

config/development.json
https://tools.hmcts.net/jira/browse/CUIRA-208
updated max age to 30 min
=> maxAge 30 min

src/main/controllers/dataController.ts
check if existing details exist before setting
=> check if details exist before setting

charts/cui-ra/Chart.yaml
=> change chart version

src/main/resources/translation/cy/common.json, src/main/resources/translation/en/common.json, src/main/views/forms/base.njk, src/main/views/review.njk, src/main/views/template.njk
https://tools.hmcts.net/jira/browse/CUIRA-210
https://tools.hmcts.net/jira/browse/CUIRA-212
added title and lang based on lang selected
=> C UI ra 210

src/main/views/review.njk, src/main/views/template.njk
https://tools.hmcts.net/jira/browse/CUIRA-211
https://tools.hmcts.net/jira/browse/CUIRA-213
aria labels on review page to separate links
aria label on feedback to tell the user the link opens in a new tab
=> aria on feedback

src/main/resources/translation/en/services/PFL/contact.json
https://tools.hmcts.net/jira/browse/CUIRA-215
added gov link class to demo footer
=> link color

src/main/views/cookies.njk
https://tools.hmcts.net/jira/browse/CUIRA-221
added cookie content in welsh and english
=> cookie page welsh and english

src/main/builders/payloadBuilder.ts, src/main/managers/dataManager.ts
fixed outbound payload 
and time to iso
=> fixed payload and time to iso

src/main/demo/data/demo-payload.json, src/main/interfaces/payload.ts, src/main/processors/flagProcessor.ts, src/main/schemas/InboundPayload.ts, src/test/unit/data/data-processor-results-welsh.json, src/test/unit/data/data-processor-results.json
allow payload where dateTimeModified does not have to be set
=> C UI ra schema

src/main/modules/nunjucks/index.ts
https://tools.hmcts.net/jira/browse/CUIRA-221
attempt to fix welsh translations
=> use welsh session and not local to setLocale

src/main/modules/nunjucks/index.ts, src/main/resources/translation/cy/common.json, src/main/resources/translation/en/common.json, src/main/resources/translation/en/services/PFL/header.json
updated the __t function to use lang when getting translations instead of using fallback
=> changed how languages are translated

src/main/managers/newFlagsManager.ts, src/main/resources/translation/cy/common.json, src/main/views/review.njk
fixed a bug where removing flags deleted the parent when it should not.
added welsh translation for single page input
added user input intop the change button aria label
=> bug fix - dont delete parent if there are more than 1 item in child

src/main/processors/formProcessor.ts
https://tools.hmcts.net/jira/browse/CUIRA-231
fixed validation bug for list when in welsh
=> welsh validation bug fix for list item

src/main/demo/data/BAA2-processor-results.json, src/main/demo/data/BAA5-processor-results.json
update mock data form BAA2 and BAA5
=> new mock data

.github/workflows/checks.yml, config/default.json, config/production.json, src/test/config.ts, src/test/functional/features/new-Journey.feature, src/test/steps/commonsteps.ts
https://tools.hmcts.net/jira/browse/CUIRA-230
enabled automated tests and set url to local in the event one is not passed.
=> enabled tests and set local url

src/main/demo/data/data-processor-results-welsh.json, src/main/demo/data/data-processor-results.json, src/main/resources/configs/services/ABA5.json, src/test/steps/commonsteps.ts
added other back in to mock and removed chair
=> added other back but removed chair

charts/cui-ra/Chart.yaml, charts/cui-ra/values.yaml, src/main/app.ts, src/main/assets/manifest.json, src/main/builders/payloadBuilder.ts, src/main/controllers/reviewController.ts, src/main/middlewares/requireIdam.ts, src/main/modules/helmet/index.ts, src/main/modules/nunjucks/index.ts, src/main/resources/translation/cy/services/PFL/footer.json, src/main/resources/translation/en/services/PFL/footer.json, src/main/views/template.njk, src/test/unit/tests/controllers/reviewController.test.ts, webpack/govukFrontend.js
https://tools.hmcts.net/jira/browse/CUIRA-179
Different links based on service, env and language
=> CUIRA-179 load different env urls for footer links

.pnp.cjs, package.json, src/main/controllers/reviewController.ts, src/test/a11y/a11y.ts, src/test/unit/data/existing-processor-results.json, src/test/unit/data/flags-payload.json, src/test/unit/tests/controllers/reviewController.test.ts, yarn.lock
https://tools.hmcts.net/jira/browse/CUIRA-262
Make active/approved flags editable
=> CUIRA-262 make active requests editable

src/main/views/forms/checkbox-group.njk, src/main/views/forms/radio-group.njk, src/main/views/forms/type-ahead.njk
https://tools.hmcts.net/jira/browse/CUIRA-238
Correctly pass information for substitution
=> CUIRA-238 correctly pass information for substitution

src/main/controllers/dataController.ts, src/main/routes.ts
https://tools.hmcts.net/jira/browse/CUIRA-260
Clear session history on journey restart.
Do not add root page to session history.
=> CUIRA-260 clear session history on start, do not store home in history

infrastructure/main.tf
CUIRA-261
Create app insights connection string separately, so the build doesn't fail.
=> CUIRA-261 create app insights connection string

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CUIRA-259
Install playwright before running functional tests
=> install playwright before functional tests

src/main/views/review.njk
https://tools.hmcts.net/jira/browse/CUIRA-239
Replace tables with lists to display user selections
=> CUIRA-239 replace tables with lists on review page

Jenkinsfile_nightly
Fix typo in Jenkins nightly pipeline
=> CUIRA-271 fix typo

charts/cui-ra/Chart.yaml, charts/cui-ra/values.yaml, config/default.json, infrastructure/main.tf, src/main/modules/appinsights/index.ts, src/main/modules/properties-volume/index.ts, src/main/processors/flagProcessor.ts
https://tools.hmcts.net/jira/browse/CUIRA-261
Replace app insights "instrumentation key" with "connection string"
=> CUIRA-261 replace appinsights instrumentation key with connection string

Jenkinsfile_nightly, src/main/app.ts
https://tools.hmcts.net/jira/browse/CUIRA-271
Added permissions policy for most common and widely supported features
=> CUIRA-271 update permissions policy

src/main/resources/translation/cy/flags.json, src/main/resources/translation/en/flags.json
https://tools.hmcts.net/jira/browse/CUIRA-277
Updated error messages that are shown when no selection has been made
=> CUIRA-277 error messages on no fields selected

Jenkinsfile_CNP, charts/cui-ra/Chart.yaml, charts/cui-ra/values.yaml, src/main/modules/properties-volume/index.ts
=> extract redis-host to property

Jenkinsfile_CNP, charts/cui-ra/Chart.yaml, charts/cui-ra/values.yaml, src/main/modules/properties-volume/index.ts
=> Revert "extract redis-host to property"

Jenkinsfile_CNP, src/main/modules/session/index.ts
https://tools.hmcts.net/jira/browse/CUIRA-291
Keep connection alive using ping for 60secs
=> CUIRA-291 keep connection alive for 60sec

src/main/views/overview.njk
https://tools.hmcts.net/jira/browse/CUIRA-292
=> CUIRA-292 show selected options in Welsh, if Welsh language is selected

package.json, src/main/managers/newFlagsManager.ts, src/main/resources/translation/en/flags.json, src/test/functional/features/error-does-not-clear-parent.feature, src/test/steps/commonsteps.ts, src/test/unit/tests/managers/newFlagsManager.test.ts, yarn.lock
https://tools.hmcts.net/jira/browse/CUIRA-279
Do not de-select parent if submitting empty form page
=> CUIRA-279 do not de-select parent on submitting empty form page

src/main/modules/session/index.ts, src/main/services/redis.ts
https://tools.hmcts.net/jira/browse/CUIRA-291
=> Add ping in every minute

charts/cui-ra/Chart.yaml, charts/cui-ra/values.yaml
https://tools.hmcts.net/jira/browse/CUIRA-281
Enable spotInstances
=> CUIRA-281 enable spot instances

src/main/assets/scss/main.scss, src/main/views/overview.njk
https://tools.hmcts.net/jira/browse/CUIRA-269
Replace table with list items in overview page
=> CUIRA-269 replace table with list in overview page

charts/cui-ra/Chart.yaml, charts/cui-ra/values.yaml, config/custom-environment-variables.json, config/default.json, config/test.json, src/main/middlewares/serviceAuthentication.ts, src/test/unit/tests/middlewares/serviceAuthentication.test.ts
https://tools.hmcts.net/jira/browse/CUIRA-294
Added check to allow services only in whitelist
=> CUIRA-294 allowed s2s validation

src/main/builders/formBuilder.ts, src/main/controllers/homeController.ts, src/main/utilities/customSort.ts, src/test/unit/tests/controllers/homeController.test.ts, src/test/unit/tests/utilities/customSort.test.ts
https://tools.hmcts.net/jira/browse/CUIRA-296
=> CUIRA-296 sort overview page flags alphabetically

src/main/app.ts
=> Fix zaproxy reported issues

src/main/resources/translation/cy/errors/500.json, src/main/resources/translation/en/errors/500.json, src/main/views/error/500.njk
[CUIRA-327](https://tools.hmcts.net/jira/browse/CUIRA-327)
Add error page link back to service
=> CUIRA-327 shutter page link

charts/cui-ra/Chart.yaml, charts/cui-ra/values.yaml, config/default.json
https://tools.hmcts.net/jira/browse/CUIRA-298
Change PRL service name in whitelist to match what PRL use
=> CUIRA-298 whitelist prl service

.pnp.cjs, package.json, src/test/unit/tests/builders/formBuilder.test.ts, yarn.lock
Master is failing because of code coverage on the formbuilder. added unit tests to cover formbuilder
=> added unit tests for form builder

src/main/builders/formBuilder.ts, src/main/constants/errorMessages.ts, src/test/unit/tests/builders/formBuilder.test.ts
Sonorcloud stated that the formbuilder required [Refactor this function to reduce its Cognitive Complexity from 17 to the 15 allowed.](https://sonarcloud.io/project/issues?open=AY6E-Qm6C8M6G5LMZN9T&id=cui-ra)
that code coverage was less than the 80%
the formbuilder has been updated to be more maintainable and more unit tests have been added to cover all the options
=> formbuilder should now be more maintainable

Jenkinsfile_CNP
remove playwright cache in jenkins before running install
=> remove playwright cache

src/main/controllers/demoController.ts, src/main/demo/data/data-processor-results-party.json, src/main/resources/configs/default.json
party demo with only the 3 items
made sure to set master title on demo
added config to hide other from party level
=> new demo data

src/main/views/template.njk
https://tools.hmcts.net/jira/browse/CUIRA-242
if service name is pressed redirect back to invoking service. i have hooked the service name back to the cancel method to achieve this
=> redirect back to invoking service if service name pressed

charts/cui-ra/Chart.yaml, charts/cui-ra/values.aat.template.yaml, charts/cui-ra/values.preview.template.yaml, charts/cui-ra/values.yaml, config/custom-environment-variables.json, config/default.json, config/development.json, config/production.json, src/main/modules/nunjucks/index.ts, src/main/views/dynatrace/head.njk
https://tools.hmcts.net/jira/browse/CUIRA-373
added extra environment variable to know when the application is running in prod
added prod dynatrace script.
script is selected based on environment variable
=> dynatrace for prod

src/main/controllers/reviewController.ts, src/test/unit/tests/controllers/reviewController.test.ts
https://tools.hmcts.net/jira/browse/PCQ-1904
Validate url
=> PCQ-1904 cuira fortify scan fix

src/main/constants/errorMessages.ts, src/main/controllers/reviewController.ts, src/test/unit/tests/controllers/reviewController.test.ts
https://tools.hmcts.net/jira/browse/PCQ-1904
Test cases added for new code
=> PCQ-1904 test cases added

charts/cui-ra/values.aat.template.yaml, charts/cui-ra/values.preview.template.yaml
Increase dev memory request and limit
=> Increase dev memory requests and limits

.pnp.cjs, package.json, yarn.lock
=> fix-nanoid-dependency

src/main/controllers/dataController.ts, src/main/controllers/reviewController.ts
To have better visibility of what is happening, log service provided callback url
=> log callback url

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CME-235
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> CME235: bump redis provider 4.x

charts/cui-ra/Chart.yaml
Bump nodejs chart to OCI version
=> Bump nodejs chart to oci compliant

src/main/modules/appinsights/index.ts
https://tools.hmcts.net/jira/browse/LAU-1120
Disable dependency logs
=> LAU-1120 disable dependency logs

src/main/modules/helmet/index.ts
Add CSP for googletagamaner  
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> Add CSP for google tag manager.

charts/cui-ra/Chart.yaml, charts/cui-ra/values.yaml
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> Fix is dev

src/test/java/build.gradle
=> Update fortify client

src/main/views/overview.njk, src/main/views/review.njk
https://tools.hmcts.net/jira/browse/CUIRA-396
Remove extra <br> element from other option
=> CUIRA-396 remove extra br element

src/test/java/build.gradle
https://tools.hmcts.net/jira/browse/CME-515
Replace jitpack with azure artifactory
=> CME-535 replace jitpack with azure

.pnp.cjs, package.json, yarn.lock
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> update healthcheck dependency
